// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8X0-1kFAhPgjujSBkC3WsF937GnekgYY',
    appId: '1:126718379030:web:b3665e63132927c8512137',
    messagingSenderId: '126718379030',
    projectId: 'ecommercepushnotificatio-5ac28',
    authDomain: 'ecommercepushnotificatio-5ac28.firebaseapp.com',
    storageBucket: 'ecommercepushnotificatio-5ac28.firebasestorage.app',
    measurementId: 'G-4B49CLPB58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-M9tT6Nw7qaNvJ14oE7MMRnTSwRq81ws',
    appId: '1:126718379030:android:57dfb9a8c0564641512137',
    messagingSenderId: '126718379030',
    projectId: 'ecommercepushnotificatio-5ac28',
    storageBucket: 'ecommercepushnotificatio-5ac28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAit9oUe8qnVjVNUMTOeyFebKRHsFDHIig',
    appId: '1:126718379030:ios:8520ed51a17b8f8a512137',
    messagingSenderId: '126718379030',
    projectId: 'ecommercepushnotificatio-5ac28',
    storageBucket: 'ecommercepushnotificatio-5ac28.firebasestorage.app',
    iosBundleId: 'com.nobmakara.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAit9oUe8qnVjVNUMTOeyFebKRHsFDHIig',
    appId: '1:126718379030:ios:8520ed51a17b8f8a512137',
    messagingSenderId: '126718379030',
    projectId: 'ecommercepushnotificatio-5ac28',
    storageBucket: 'ecommercepushnotificatio-5ac28.firebasestorage.app',
    iosBundleId: 'com.nobmakara.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8X0-1kFAhPgjujSBkC3WsF937GnekgYY',
    appId: '1:126718379030:web:f66a061210da783b512137',
    messagingSenderId: '126718379030',
    projectId: 'ecommercepushnotificatio-5ac28',
    authDomain: 'ecommercepushnotificatio-5ac28.firebaseapp.com',
    storageBucket: 'ecommercepushnotificatio-5ac28.firebasestorage.app',
    measurementId: 'G-HMM5D39R90',
  );
}
